"""
Intentionally vulnerable HTTP/1.1 front-end for the CL.TE lab.

The front-end uses Content-Length to delimit the request body and forwards
that exact number of bytes to the backend without normalizing or removing
Transfer-Encoding.

It also enforces the /admin ACL on the request line that it parses. In a
CL.TE desync, /admin can therefore be hidden inside the body of an allowed
request and interpreted separately by the backend.
"""
import socket
import threading

HOST = "0.0.0.0"
PORT = 8080
BACKEND_HOST = "app"
BACKEND_PORT = 8000

MAX_HEADER_SIZE = 32 * 1024
SOCKET_TIMEOUT = 10


def recv_until(sock, marker, initial=b""):
    """Read until marker is present, returning (data, remainder)."""
    buf = initial
    while marker not in buf:
        if len(buf) > MAX_HEADER_SIZE:
            raise ValueError("HTTP headers too large")
        data = sock.recv(4096)
        if not data:
            raise ConnectionError("client closed connection")
        buf += data
    pos = buf.index(marker) + len(marker)
    return buf[:pos], buf[pos:]


def parse_request_head(head):
    """Return (method, path, headers) from a raw HTTP request head."""
    text = head.decode("iso-8859-1")
    lines = text[:-4].split("\r\n")
    request_line = lines[0].split(" ")
    if len(request_line) < 2:
        raise ValueError("malformed request line")

    method, path = request_line[0], request_line[1]
    headers = {}
    for line in lines[1:]:
        if ":" in line:
            key, value = line.split(":", 1)
            headers[key.strip().lower()] = value.strip()
    return method, path, headers


def recv_exact(sock, amount, initial=b""):
    """Return exactly amount bytes, preserving any bytes already received."""
    buf = initial
    while len(buf) < amount:
        data = sock.recv(min(4096, amount - len(buf)))
        if not data:
            raise ConnectionError("client closed before Content-Length bytes arrived")
        buf += data
    return buf[:amount], buf[amount:]


def relay_response(backend, client):
    """Relay backend bytes to the client until the backend closes."""
    while True:
        data = backend.recv(4096)
        if not data:
            break
        client.sendall(data)


def handle_client(client, addr):
    client.settimeout(SOCKET_TIMEOUT)
    backend = None
    pending = b""
    backend_pending = b""

    try:
        backend = socket.create_connection((BACKEND_HOST, BACKEND_PORT), timeout=SOCKET_TIMEOUT)
        backend.settimeout(SOCKET_TIMEOUT)

        while True:
            # Front-end parses one request using Content-Length.
            head, pending = recv_until(client, b"\r\n\r\n", pending)
            method, path, headers = parse_request_head(head)

            print(f"[frontend] {addr} -> {method} {path}", flush=True)

            # ACL is applied only to the request the front-end actually parses.
            if path == "/admin":
                response = (
                    b"HTTP/1.1 403 Forbidden\r\n"
                    b"Content-Type: text/plain; charset=utf-8\r\n"
                    b"Content-Length: 10\r\n"
                    b"Connection: close\r\n"
                    b"\r\n"
                    b"Forbidden\n"
                )
                client.sendall(response)
                return

            try:
                content_length = int(headers.get("content-length", "0"))
            except ValueError:
                raise ValueError("invalid Content-Length")

            if content_length < 0 or content_length > 10 * 1024 * 1024:
                raise ValueError("invalid Content-Length")

            # CRITICAL VULNERABILITY:
            # We trust Content-Length even when Transfer-Encoding is present,
            # and forward the original headers/body byte-for-byte.
            body, pending = recv_exact(client, content_length, pending)
            request = head + body
            backend.sendall(request)

            # Read the response for this front-end request. We deliberately
            # keep the backend connection alive so the smuggled request can
            # be processed on the same backend TCP stream.
            #
            # Responses have Content-Length, so read exactly one response and
            # leave subsequent responses for the next frontend request.
            response_head, backend_pending = recv_until_backend(
                backend, b"\r\n\r\n", backend_pending
            )
            response_length = parse_response_headers(response_head)
            response_body, backend_pending = recv_exact(
                backend, response_length, backend_pending
            )
            client.sendall(response_head + response_body)

            # Forward any response bytes already buffered (for example the
            # response generated by the smuggled GET /admin), then collect
            # bytes that arrive immediately afterwards.
            if backend_pending:
                client.sendall(backend_pending)
                backend_pending = b""

            backend.settimeout(0.15)
            try:
                while True:
                    extra = backend.recv(4096)
                    if not extra:
                        return
                    client.sendall(extra)
            except socket.timeout:
                pass
            finally:
                backend.settimeout(SOCKET_TIMEOUT)

            if not pending:
                # Wait for another request on the client connection.
                continue

    except (ConnectionError, TimeoutError, socket.timeout, ValueError, OSError) as exc:
        print(f"[frontend] {addr} closed: {exc}", flush=True)
    finally:
        if backend is not None:
            backend.close()
        client.close()


def recv_until_backend(sock, marker, initial=b""):
    buf = initial
    while marker not in buf:
        data = sock.recv(4096)
        if not data:
            raise ConnectionError("backend closed connection")
        buf += data
    pos = buf.index(marker) + len(marker)
    return buf[:pos], buf[pos:]


def parse_response_headers(head):
    text = head.decode("iso-8859-1")
    for line in text[:-4].split("\r\n")[1:]:
        if line.lower().startswith("content-length:"):
            return int(line.split(":", 1)[1].strip())
    return 0


def run():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind((HOST, PORT))
    server.listen(50)
    print(f"Vulnerable CL.TE frontend listening on {HOST}:{PORT}", flush=True)

    while True:
        client, addr = server.accept()
        threading.Thread(target=handle_client, args=(client, addr), daemon=True).start()


if __name__ == "__main__":
    run()
